# Generated by Django 4.1.5 on 2023-12-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_index', models.CharField(max_length=700, verbose_name='Индекс профиля')),
                ('address', models.CharField(max_length=700, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=300, verbose_name='Номер телефона')),
                ('products', models.TextField(verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
