# Generated by Django 5.0.1 on 2024-01-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/%Y/', verbose_name='Изображение слайда')),
                ('text', models.TextField(verbose_name='Верхний текст(не обязательно)')),
                ('url', models.SlugField(verbose_name='URL(не обязательно)')),
            ],
        ),
    ]
