# Generated by Django 5.0.1 on 2024-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='headline',
            field=models.CharField(default='None', max_length=255, verbose_name='Загаловок'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.TextField(default='None', verbose_name='Верхний текст(не обязательно)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.SlugField(default='None', verbose_name='URL(не обязательно)'),
        ),
    ]
